"""add Project Model

Revision ID: 3c1cf09049e6
Revises: 271a6a190066
Create Date: 2014-07-27 11:26:40.603738

"""

# revision identifiers, used by Alembic.
revision = '3c1cf09049e6'
down_revision = '271a6a190066'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('bugget', sa.String(length=50), nullable=True),
    sa.Column('period', sa.String(length=50), nullable=True),
    sa.Column('desc', sa.Text(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project')
    ### end Alembic commands ###
