"""add hire type to project

Revision ID: 6cdaa960981
Revises: 3c1cf09049e6
Create Date: 2014-07-27 15:29:37.958488

"""

# revision identifiers, used by Alembic.
revision = '6cdaa960981'
down_revision = '3c1cf09049e6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('hire_type', sa.String(length=50), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'hire_type')
    ### end Alembic commands ###
